/***************************************************************
 * Name:      StackandQueueVisualizerMain.cpp
 * Purpose:   C++ Fall 2025 Final Project
 * Author:    Samantha Scott (sscot068@fiu.edu)
 * Created:   2025-11-28
 * Copyright: Samantha Scott ()
 * License:
 **************************************************************/

#include "wx_pch.h" //Include precompiled header used by wxWidgets projects
#include "StackandQueueVisualizerMain.h" //Include our custom header fie
#include <wx/msgdlg.h> //Include for wxMessageBox dialogs

//(*InternalHeaders(StackandQueueVisualizerFrame)
#include <wx/intl.h>
#include <wx/string.h>
//*)

// Helper enum and function used to display build information in the "About" dialog.
enum wxbuildinfoformat {
    short_f, long_f };

// Returns a string describing the wxWidgets build.
// If "long_f" is passed, extra details such as OS and Unicode/ANSI are appended.
wxString wxbuildinfo(wxbuildinfoformat format)
{
    wxString wxbuild(wxVERSION_STRING);   // Base version string, e.g. "wxWidgets 3.1.7"

    if (format == long_f )
    {
#if defined(__WXMSW__)
        wxbuild << _T("-Windows");        // Application is built for Windows
#elif defined(__UNIX__)
        wxbuild << _T("-Linux");          // Application is built for Linux
#endif

#if wxUSE_UNICODE
        wxbuild << _T("-Unicode build");  // Using Unicode build of wxWidgets
#else
        wxbuild << _T("-ANSI build");     // Using ANSI build of wxWidgets
#endif // wxUSE_UNICODE
    }

    return wxbuild;
}

//------------------------------------------------------------------//
//                          Control IDs
//------------------------------------------------------------------//

// wxWidgets uses numeric IDs to uniquely identify controls and menu items.
// wxNewId() generates a new unique ID and one is assigned to each identifier we declared in the header.
//(*IdInit(StackandQueueVisualizerFrame)
const wxWindowID StackandQueueVisualizerFrame::ID_STATICTEXT1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_STATICTEXT2 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_TEXTCTRL1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_BUTTON1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_BUTTON2 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_LISTBOX1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_PANEL1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_STATICTEXT3 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_STATICTEXT4 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_TEXTCTRL2 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_BUTTON3 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_BUTTON4 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_LISTBOX2 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_PANEL2 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_NOTEBOOK1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_MENUITEM1 = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::idMenuAbout = wxNewId();
const wxWindowID StackandQueueVisualizerFrame::ID_STATUSBAR1 = wxNewId();
//*)

//------------------------------------------------------------------//
//                       Event table
//-----------------------------------------------------------------//

//Events are binded dynamically (not static) so this event table is currently empty
BEGIN_EVENT_TABLE(StackandQueueVisualizerFrame,wxFrame)
    //(*EventTable(StackandQueueVisualizerFrame)
    //*)
END_EVENT_TABLE()

//-----------------------------------------------------------------//
//              Frame constructor - builds the entire GUI
//          The code within this constructor was automatically
//          generated based on the layout I selected using wxSmith
//-----------------------------------------------------------------//

StackandQueueVisualizerFrame::StackandQueueVisualizerFrame(wxWindow* parent,wxWindowID id)
{
    // Local pointers to sizers, menus, and menu items automatically generated by wxSmith.
    // These are used only inside the constructor to build the layout.
    //(*Initialize(StackandQueueVisualizerFrame)
    wxBoxSizer* BoxSizer2;
    wxBoxSizer* BoxSizer3;
    wxBoxSizer* BoxSizer4;
    wxMenu* Menu1;
    wxMenu* Menu2;
    wxMenuBar* MenuBar1;
    wxMenuItem* MenuItem1;
    wxMenuItem* MenuItem2;

    Create(parent, wxID_ANY, _("Samantha\'s Stack and Queue Visualizer"), wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE, _T("wxID_ANY"));
    SetClientSize(wxSize(800,500));
    Notebook1 = new wxNotebook(this, ID_NOTEBOOK1, wxPoint(512,360), wxDefaultSize, 0, _T("ID_NOTEBOOK1"));
    StackPanel = new wxPanel(Notebook1, ID_PANEL1, wxPoint(-1,-1), wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL1"));
    StackPanel->SetMinSize(wxSize(-1,-1));
    StackPanel->SetMaxSize(wxSize(-1,-1));
    BoxSizer1 = new wxBoxSizer(wxVERTICAL);
    StackLabel = new wxStaticText(StackPanel, ID_STATICTEXT1, _(" STACK (LIFO - Last In First Out) \n**To add an integer to the stack :  Enter the number then select Push**\n**To remove an integer from the stack: select Pop**"), wxDefaultPosition, wxSize(790,85), 0, _T("ID_STATICTEXT1"));
    BoxSizer1->Add(StackLabel, 1, wxALL|wxSHAPED, 1);
    BoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    Value = new wxStaticText(StackPanel, ID_STATICTEXT2, _("      Enter an integer:"), wxDefaultPosition, wxSize(56,26), 0, _T("ID_STATICTEXT2"));
    BoxSizer2->Add(Value, 1, wxALL|wxEXPAND, 5);
    TextCtrl1 = new wxTextCtrl(StackPanel, ID_TEXTCTRL1, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_TEXTCTRL1"));
    BoxSizer2->Add(TextCtrl1, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    pushButton = new wxButton(StackPanel, ID_BUTTON1, _("Push"), wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_BUTTON1"));
    BoxSizer2->Add(pushButton, 1, wxALL, 5);
    popButton = new wxButton(StackPanel, ID_BUTTON2, _("Pop"), wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_BUTTON2"));
    BoxSizer2->Add(popButton, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    BoxSizer1->Add(BoxSizer2, 1, wxALL|wxSHAPED, 5);
    StackList = new wxListBox(StackPanel, ID_LISTBOX1, wxDefaultPosition, wxSize(782,306), 0, 0, 0, wxDefaultValidator, _T("ID_LISTBOX1"));
    BoxSizer1->Add(StackList, 1, wxALL|wxEXPAND, 5);
    StackPanel->SetSizer(BoxSizer1);
    QueuePanel = new wxPanel(Notebook1, ID_PANEL2, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL2"));
    BoxSizer3 = new wxBoxSizer(wxVERTICAL);
    QueueLabel = new wxStaticText(QueuePanel, ID_STATICTEXT3, _(" QUEUE (FIFO - First In First Out) \n**To add an integer to the queue :  Enter the number then select Enqueue**\n**To remove an integer from the queue: select Dequeue**"), wxDefaultPosition, wxSize(790,82), 0, _T("ID_STATICTEXT3"));
    BoxSizer3->Add(QueueLabel, 1, wxALL|wxSHAPED, -1);
    BoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    Value2 = new wxStaticText(QueuePanel, ID_STATICTEXT4, _("     Enter an integer:"), wxDefaultPosition, wxSize(56,26), 0, _T("ID_STATICTEXT4"));
    BoxSizer4->Add(Value2, 1, wxALL|wxEXPAND, 5);
    TextCtrl2 = new wxTextCtrl(QueuePanel, ID_TEXTCTRL2, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_TEXTCTRL2"));
    BoxSizer4->Add(TextCtrl2, 1, wxALL|wxEXPAND, 5);
    queueButton = new wxButton(QueuePanel, ID_BUTTON3, _("Enqueue"), wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_BUTTON3"));
    BoxSizer4->Add(queueButton, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    dequeueButton = new wxButton(QueuePanel, ID_BUTTON4, _("Dequeue"), wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_BUTTON4"));
    BoxSizer4->Add(dequeueButton, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    BoxSizer3->Add(BoxSizer4, 1, wxALL|wxSHAPED, 5);
    QueueList = new wxListBox(QueuePanel, ID_LISTBOX2, wxDefaultPosition, wxSize(782,306), 0, 0, 0, wxDefaultValidator, _T("ID_LISTBOX2"));
    BoxSizer3->Add(QueueList, 1, wxALL|wxEXPAND, 5);
    QueuePanel->SetSizer(BoxSizer3);
    Notebook1->AddPage(StackPanel, _("Stack"), false);
    Notebook1->AddPage(QueuePanel, _("Queue"), false);
    MenuBar1 = new wxMenuBar();
    Menu1 = new wxMenu();
    MenuItem1 = new wxMenuItem(Menu1, ID_MENUITEM1, _("Quit\tAlt-F4"), _("Quit the application"), wxITEM_NORMAL);
    Menu1->Append(MenuItem1);
    MenuBar1->Append(Menu1, _("&File"));
    Menu2 = new wxMenu();
    MenuItem2 = new wxMenuItem(Menu2, idMenuAbout, _("About\tF1"), _("Show info about this application"), wxITEM_NORMAL);
    Menu2->Append(MenuItem2);
    MenuBar1->Append(Menu2, _("Help"));
    SetMenuBar(MenuBar1);
    StatusBar1 = new wxStatusBar(this, ID_STATUSBAR1, 0, _T("ID_STATUSBAR1"));
    int __wxStatusBarWidths_1[1] = { -1 };
    int __wxStatusBarStyles_1[1] = { wxSB_NORMAL };
    StatusBar1->SetFieldsCount(1,__wxStatusBarWidths_1);
    StatusBar1->SetStatusStyles(1,__wxStatusBarStyles_1);
    SetStatusBar(StatusBar1);
    Center();

    Connect(ID_BUTTON1, wxEVT_COMMAND_BUTTON_CLICKED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OnpushButtonClick);
    Connect(ID_BUTTON2, wxEVT_COMMAND_BUTTON_CLICKED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OnpopButtonClick);
    Connect(ID_BUTTON3, wxEVT_COMMAND_BUTTON_CLICKED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OnqueueButtonClick);
    Connect(ID_BUTTON4, wxEVT_COMMAND_BUTTON_CLICKED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OndequeueButtonClick);
    Connect(ID_MENUITEM1, wxEVT_COMMAND_MENU_SELECTED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OnQuit);
    Connect(idMenuAbout, wxEVT_COMMAND_MENU_SELECTED, (wxObjectEventFunction)&StackandQueueVisualizerFrame::OnAbout);
    //*)
}

StackandQueueVisualizerFrame::~StackandQueueVisualizerFrame() //Frame Class Destructor
{
    //(*Destroy(StackandQueueVisualizerFrame)
    //*)
}

//--------------------------------------------------------------//
//                  EVENT HANDLERS
//--------------------------------------------------------------//

//On Quit Function definition-closes the main window and application
void StackandQueueVisualizerFrame::OnQuit(wxCommandEvent& event)
{
    Close(); //Call Close function
}

//On About Function definition -
void StackandQueueVisualizerFrame::OnAbout(wxCommandEvent& event)
{
    wxString msg = wxbuildinfo(long_f); // gets buildinfo and store it as a wxString
    wxMessageBox(msg, _("About Samantha's Stack and Queue Visualizer")); //displays build info and custom title
}

//Event Handler for Push button click event
void StackandQueueVisualizerFrame::OnpushButtonClick(wxCommandEvent& event)
{
    long val; //member variable of long type

    //if the input text cannot be converted to a number print an error message
    //Dereference TextCtrl1 pointer and use chain calling to access GetValue and ToLong methods
    if(!TextCtrl1->GetValue().ToLong(&val)){
        wxMessageBox("Input Error!","Please enter a valid integer", wxOK | wxICON_ERROR, this);
        return;
    }

    m_stack.push_back((int)val); //Add input to the top of of the stack by calling the push_back method
    RefreshStackDisplay(); //Call RefreshStackDisplay function to show new Stack
    TextCtrl1->Clear(); //Clear input text box
}

//Event Handler for Pop button click event
void StackandQueueVisualizerFrame::OnpopButtonClick(wxCommandEvent& event)
{
    //if the stack is empty we cannot pop so display error message
    //Call empty method on the m_stack object
    if (m_stack.empty()){
        wxMessageBox("The stack is empty.","Oops!", wxOK | wxICON_INFORMATION, this);
        return;
    }

    m_stack.pop_back(); //Remove the element at the top of the stack (LIFO)
    RefreshStackDisplay(); //Call RefreshStackDisplay function to show new Stack

}

//Event Handler for Enqueue button click event
void StackandQueueVisualizerFrame::OnqueueButtonClick(wxCommandEvent& event)
{
    long val; //member variable of long type

    //if the input text cannot be converted to a number print an error message
    //Dereference TextCtrl2 pointer and use chain calling to access GetValue and ToLong methods
    if(!TextCtrl2->GetValue().ToLong(&val)){
        wxMessageBox("Input Error!","Please enter a valid integer", wxOK | wxICON_ERROR, this);
        return;
    }

    m_queue.push_back((int)val); //Add input to the back of of the queue by calling the push method
    RefreshQueueDisplay(); //Call RefreshQueueDisplay function to show new Queue
    TextCtrl2->Clear(); //Clear input text box
}

//Event Handler for Dequeue button click event
void StackandQueueVisualizerFrame::OndequeueButtonClick(wxCommandEvent& event)
{
    //if the queue is empty we cannot remove an element so display error message
    //Call empty method on the m_queue object
    if (m_queue.empty()){
        wxMessageBox("The queue is empty.","Oops!", wxOK | wxICON_INFORMATION, this);
        return;
    }

    m_queue.pop_front(); //Remove the element at the front of the queue (FIFO)
    RefreshQueueDisplay(); //Call RefreshQueueDisplay function to show new Queue

}

//--------------------------------------------------------------//
//                 Visual Display Function definitions
//--------------------------------------------------------------//

void StackandQueueVisualizerFrame::RefreshStackDisplay(){
    StackList->Clear(); //clear previous display by dereferencing and calling the Clear function

    //for loop to display contents of the stack
    //decrementing for loop to show the last element of the stack at the top of the list
    //could have also used a for_each algorithm with a reverse iterator and an append function to achieve the same results
    for(int i=(int)m_stack.size()-1; i>=0; --i){
        //Deference StackList pointer to access the append function
        // Add a formatted String with the stack element to the list
        StackList->Append(wxString::Format("%d", m_stack[i]));
    }
}

void StackandQueueVisualizerFrame::RefreshQueueDisplay(){
    QueueList->Clear(); //clear previous display by dereferencing and calling the Clear function

    //for loop to display contents of the queue
    //incrementing for loop to show the first element in the queue at the top of the list
    //could have also used a for_each algorithm with a forward iterator and an append function to achieve the same results
    for (int i=0; i < m_queue.size(); ++i){
        //Deference QueueList pointer to access the append function
        // Add a formatted String with the queue element to the list
        QueueList->Append(wxString::Format("%d", m_queue[i]));
    }
}
