/***************************************************************
 * Name:      StackandQueueVisualizerMain.h
 * Purpose:   Defines Application Frame
 * Author:    Samantha Scott (sscot068@fiu.edu)
 * Created:   2025-11-28
 * Copyright: Samantha Scott ()
 * License:
 **************************************************************/

#ifndef STACKANDQUEUEVISUALIZERMAIN_H //header guard if not defined - if it's true the variable has not been defined
#define STACKANDQUEUEVISUALIZERMAIN_H//preprocessor directive that defines STACKANDQUEVISUALIZERMAIN_H as preprocessor variable

//include headers for different wxControls used in the main application window
//(*Headers(StackandQueueVisualizerFrame)
#include <wx/button.h>
#include <wx/frame.h>
#include <wx/listbox.h>
#include <wx/menu.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statusbr.h>
#include <wx/textctrl.h>
//*)

#include <vector> //Include vector from the STL to make stack object (Last In First Out)
#include <deque>  //Include deque from the STL to make queue object  (First In First Out)

//Main Application Window/Frame class
//StackandQueueVisualizerFrame used to define the GUI,event handling and logic behind the application
class StackandQueueVisualizerFrame: public wxFrame //inherits from the wxFrame at the public level
{
    public:

        StackandQueueVisualizerFrame(wxWindow* parent,wxWindowID id = -1); //constructor
        virtual ~StackandQueueVisualizerFrame();    //destructor

    private:
        // Event handler function prototypes for buttons and menu items
        //(*Handlers(StackandQueueVisualizerFrame)
        void OnQuit(wxCommandEvent& event);              // For the "Quit" menu option - closes the application
        void OnAbout(wxCommandEvent& event);             // For the "About" menu option  - shows app information
        void OnNotebook1PageChanged(wxNotebookEvent& event); // Tab changes between Stack and Queue
        void OnTextCtrl1Text(wxCommandEvent& event);     // Text changes in the first text box
        void OnpushButtonClick(wxCommandEvent& event);   // For the Push button click on the stack panel
        void OnpopButtonClick(wxCommandEvent& event);    // For the Pop button click on the stack panel
        void OnqueueButtonClick(wxCommandEvent& event);  // For the Enqueue button click on the queue panel
        void OndequeueButtonClick(wxCommandEvent& event);// For the Dequeue button click on the queue panel
        //*)

        //wxSmith automatically generated unique identifiers for each control and menu item listed here
        //(*Identifiers(StackandQueueVisualizerFrame)
        static const wxWindowID ID_STATICTEXT1;
        static const wxWindowID ID_STATICTEXT2;
        static const wxWindowID ID_TEXTCTRL1;
        static const wxWindowID ID_BUTTON1;
        static const wxWindowID ID_BUTTON2;
        static const wxWindowID ID_LISTBOX1;
        static const wxWindowID ID_PANEL1;
        static const wxWindowID ID_STATICTEXT3;
        static const wxWindowID ID_STATICTEXT4;
        static const wxWindowID ID_TEXTCTRL2;
        static const wxWindowID ID_BUTTON3;
        static const wxWindowID ID_BUTTON4;
        static const wxWindowID ID_LISTBOX2;
        static const wxWindowID ID_PANEL2;
        static const wxWindowID ID_NOTEBOOK1;
        static const wxWindowID ID_MENUITEM1;
        static const wxWindowID idMenuAbout;
        static const wxWindowID ID_STATUSBAR1;
        //*)

        // Pointer Declarations of the GUI components automatically generated by wxSmith initialized in the main.cpp file
        //(*Declarations(StackandQueueVisualizerFrame)
        wxBoxSizer* BoxSizer1;
        wxButton* dequeueButton;
        wxButton* popButton;
        wxButton* pushButton;
        wxButton* queueButton;
        wxListBox* QueueList;
        wxListBox* StackList;
        wxNotebook* Notebook1;
        wxPanel* QueuePanel;
        wxPanel* StackPanel;
        wxStaticText* QueueLabel;
        wxStaticText* StackLabel;
        wxStaticText* Value2;
        wxStaticText* Value;
        wxStatusBar* StatusBar1;
        wxTextCtrl* TextCtrl1;
        wxTextCtrl* TextCtrl2;
        //*)

        //Object Containers used to store contents of the stack and queue
        //Could have also used stack and queue containers from the STL
        //vector and deque containers are more convenient to iterator through
        std::vector<int> m_stack; //Using vector from STL to create the stack data structure
        std::deque<int> m_queue; //Using deque from STL to create the queue data structure

        //Helper Function declarations
        void RefreshStackDisplay(); //Function declaration - Refreshes Display on Stack Panel
        void RefreshQueueDisplay(); //Function declaration - Refreshes Display on Queue Panel

        // Macro used by wxWidgets to declare the event table for this class.
        DECLARE_EVENT_TABLE()
};

#endif // STACKANDQUEUEVISUALIZERMAIN_H - header guard ensures the compiler processes everything up to this
